# Generated by Django 3.1.7 on 2021-04-09 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210402_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='gonext',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='associatedGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameroles', to='api.game'),
        ),
        migrations.AlterField(
            model_name='role',
            name='playedBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerrole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='week',
            name='associatedRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleweeks', to='api.role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('playedBy', 'associatedGame')},
        ),
    ]
