# Generated by Django 3.1.7 on 2021-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_role_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='gonext',
        ),
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='order_placed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
