# Generated by Django 3.2 on 2021-04-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='isDefaultGame',
            field=models.BooleanField(default=True),
        ),
    ]
