# Generated by Django 3.1.7 on 2021-04-02 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_length', models.IntegerField()),
                ('distributorPresent', models.BooleanField()),
                ('wholesalerPresent', models.BooleanField()),
                ('active', models.BooleanField()),
                ('info_sharing', models.BooleanField(default=False)),
                ('info_delay', models.IntegerField(default=2)),
                ('holding_cost', models.FloatField(default=1)),
                ('backlog_cost', models.FloatField(default=1)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('isDefaultGame', models.BooleanField()),
                ('starting_inventory', models.IntegerField(default=0)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30)),
                ('associatedGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('downstreamPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_downstreamPlayer', to='api.role')),
                ('playedBy', models.ForeignKey(limit_choices_to={'is_instructor': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upstreamPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_upstreamPlayer', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('backlog', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('incoming_shipment', models.IntegerField()),
                ('outgoing_shipment', models.IntegerField()),
                ('order_placed', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('associatedRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
    ]
