# Generated by Django 3.1.7 on 2021-04-02 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_role_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='downstreamPlayer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_downstreamPlayer', to='api.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='playedBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='upstreamPlayer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_upstreamPlayer', to='api.role'),
        ),
    ]
