# Generated by Django 3.1.7 on 2021-04-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210402_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='playedBy',
            field=models.ForeignKey(limit_choices_to={'is_instructor': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='upstreamPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_upstreamPlayer', to='api.role'),
        ),
    ]
