# Generated by Django 3.1.7 on 2021-04-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210402_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='downstreamPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_downstreamPlayer', to='api.role'),
        ),
    ]
